caswell-rssi-leds/files/caswell-rssi-leds
caswell-rssi-leds/files/caswell-rssi-leds.init
sync-settings/files/wwan_status.sh

The uqmi utility is used to communicate with the LTE modem on the Untangle e6wl.  It is used for three things:
1.  Configuring the interface to create the actual network connection
2.  A script periodically polls the signal strength to update the rssi leds on the box
3.  The UI (via a status api) calls it to get sim details to display
It turns out that multiple instances of uqmi running at the same time can cause one or more of the instances to hang indefinitely.
The right fix here is probably to change uqmi (and possibly the driver) to allow multiple instances at the same time.  But that seemed out of scope for 1.1.
Another possible fix was to use something like flock to serialize all calls to uqmi.  This would work, but would involve changing the upstream qmi netifd protocol handler, …

Mfw 771 Fix Intermittent uqmi hangs

---

caswell-rssi-leds/files/caswell-rssi-leds.init

This will ensure we are starting from a fresh configuration.  In the
cases of a loss of power or a sysupgrade we may not have properly
shut down the LTE connection prior to rebooting.  That can leave
the modem in a state in which it thinks its connected, but isn't.
In this state, no amount of configuring the device will ever get
it back on line.  Only a modem reset will do.
MFW-802

MFW-802: caswell-rssi-leds: Reset modem at boot

---

sync-settings/files/sync-settings.init

This will ensure the configuration files written out to the system
are in sync with the current firmware image.
MFW-910

MFW-910: sync-settings: Run 'sync-settings -n' at boot

---

license-scripts/Makefile
license-scripts/files/fetch-licenses.init

Try to fetch licenses at startup if there isn't a license file.
That way a box will have the correct bandwidth limits and qos
restrictions right off the bat if a valid license for the box
already exists when the box is initially being set up.  It also
ensures that unlimited boxes like linksys and virtualbox have their
unlimited license file populated immediately
MFW-978

license-scripts: Add startup script

---

license-scripts/files/fetch-licenses.sh

While merely defining the seats is sufficient to trick the UI
into thinking virtualbox/linksys has an unlimited license, the
interface-kpbs script actually checks if the name of the license
is "untangle-node-throughput".
MFW-1000

fetch-licenses: Add "untangle-node-throughput" to fake license

---

configs/device/wrt1900/target
configs/device/wrt3200/target
configs/device/wrt32x/target

We have enabled zram-swap on the linksys devices to solve the "cannot allocate memory" error we see when some golang and
python apps attempt to spawn external processes to get status or modify system configuration. We think this will improve kernel memory management so it can better handle exec requests made by applications that have a large memory footprint. This change was applied for wrt1900, wrt3200, and wrt32x devices.

Enable zram-swap on linksys devices

---

sync-settings/files/sync-settings.init

To ensure that defaults.json is up to date with the currently running
code, re-generate it on every boot
MFW-1106

sync-settings: Refresh defaults.json on every boot

---

node-yarn/Makefile

This allows node to only get built once:
```
make[3] -C feeds/mfw/packetd compile
make[3] -C feeds/mfw/node-override host-compile
make[3] -C feeds/mfw/container compile
make[3] -C feeds/packages/libs/gdbm compile
make[3] -C feeds/mfw/node-yarn host-compile
make[3] -C feeds/mfw/ui compile
```

Force node-override as a dependency for node-yarn

---

bctid/files/bcti.cfg.sdwan

In order to work around a know issue with the bctid daemon where cached lookup is not working, we will disable the cache by setting it's size to 0.

turn off ip reputation cache in bctid

---

sync-settings/files/speedtest.sh

Fixed the speedtest.sh script so it always outputs a valid json object, either an error message that can be detected by the UI code, or the json result generated by the speedtest-cli utility. Added the --no-pre-allocate when calling speedtest-cli to prevent out of memory errors during the upload test on devices with limited memory.

Fix insufficient memory issue and improve error detection and handling

---

pyconnector/files/pyconnector.init

Correct a shell substitution that caused the host variable to be empty, see https://jira.untangle.com/browse/MFW-2200

MFW 2200: Correct shell substitution.

---

backup-scripts/files/upload-backup.sh

[MFW-2556](https://jira.untangle.com/browse/MFW-2556)
read MFW version from `/etc/os-release` (as restd reads the version info from here, refer: https://github.com/untangle/restd/blob/6aec907fba182fea9a56bd9bdffb9bd906deb9ba/services/gind/status.go#L428) and send it as a header while uploading the cloud backup.
**from the MFW logs**
```log
License found for: untangle-node-throughput
License found for: untangle-node-threat-prevention
License found for: untangle-node-sitefilter
License found for: untangle-node-geoip
License found for: untangle-node-classd
License found for: untangle-node-dboffload
License found for: untangle-node-discovery
Total licenses: 7
Licenses found, completing backup
Backing up settings to gunzipped tar archive file
Running backup
URL: …
```

MFW-2556: send version during backup upload

---

mfw-eu/files/settings_uri.js

**Jira**: https://awakesecurity.atlassian.net/browse/MFW-3190
Added uriTranslation **host: https://eu.edge.arista.com** for **uri: https://launchpad.edge.arista.com**

MFW-3190: Added uriTranslation host for eu-launchpad

---

sync-settings/Makefile
sync-settings/files/quota_cron.sh

New shell script which runs as part of cronjob. This script is currently used by Quota Manager to schedule NFT rule delete/readd after the time expires.

Quota changes

---

sync-settings/files/load-eos-config.init

Calling the load-eos-config with "-b" flag to copy the running-config to startup-config during boot up.
PR for introducing the -b flag : https://github.com/untangle/sync-settings/pull/587

MFW-3719: Adding a boot config checkout flag for load-eos-config

---

sync-settings/files/interface-watcher.init
sync-settings/files/interface_watcher.sh

Reverts untangle/mfw_feeds#206

Revert "Mfw 4007 on network device down, static routes are dropped, but not registered back on device up"

---

barney.context

Migrate barney repomaps from git notes to barney context files
Task: [MFW-5415](https://awakesecurity.atlassian.net/browse/MFW-5415)
PR target: create barney context file
[MFW-5415]: https://awakesecurity.atlassian.net/browse/MFW-5415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MFW-5415 Migrate barney repomaps from git notes to barney context files

---

sync-settings/files/product-board-name.init

It checks number of eth* devices on the board and usees it to populate the product_board name for e and q series devices.
For Q series writes Q6 as Q6e

MFW-5697: Added support for q4, q8, e4 and e8 product_board_names

---

renovate.json5

As recommended by Braney-ci/Renovate maintainers we need to overwrite rule for code.arista.io/infra/barney/barnzilla-repos if we want it to automerge.
The example from the team
packageRules: [
{
"matchDatasources": ["custom.bar"],
"matchPackageNames": ["code.arista.io/infra/barney/barnzilla-repos"], "automergeSchedule": ["at any time"]
}
]
```

overwrite automerge schedule for barnzilla-repos

---

bctid/Makefile
configs/common/openwrt_packages

**Jira**: https://awakesecurity.atlassian.net/browse/MFW-5803
1. This PR: In mfw_feeds, added cJSON dependency and enabled cJSON in openwrt_packages.
2. Related [packetd PR](https://github.com/untangle/packetd/pull/1146): In packetd, changed “catid” to “cat”, because the new bctid version requires it to be done: https://github.com/untangle/bctid/pull/157/files#diff-c71253f491e018b400f1ee33c8b044aac89feb85ebdbf8550275a56ddb14e845R24

MFW-5803: Updated cJSON dependency for bctid

---

sync-settings/Makefile

[Build #15 for mfw-release-6.1](http://jenkins.untangle.int/job/MFW%20pipeline/job/mfw-release-6.1/15/consoleFull) did not have password-manager binary. So we have added secret-manager as a dependency to sync-settings hoping that it would trigger secret-manager installation and eventually copy the password-manager binary.

Added secret-manager dependency to sync-settings

---

barney.context
pyconnector/files/pyconnector.init

From the investigation [MFW-6296](https://awakesecurity.atlassian.net/browse/MFW-6296): pyconnector was failing for E6 device on reboot.
Root Cause: In the URI translation process, wget is used to make a call to `http://127.0.0.1/api/uri/geturiwithpath/uri=$uri` without a timeout.
now for `wget` added timeout=30 with tries=1, 
tries=1 is required. Since the default is 20 retries, if the server is unreachable or the address is invalid, wget will make up to 20 attempts to reach the server.
If URI translation process fails, then fallback is added at https://github.com/untangle/mfw_feeds/blob/mfw-release-6.1/pyconnector/files/pyconnector.init#L73
[MFW-6296]: https://awakesecurity.atlassian.net/browse/MFW-6296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

Sync-settings freezes on E6 on reboot after ipsec interface creation

---

barney.yaml

https://awakesecurity.atlassian.net/browse/EFW-874
`efw_feeds` will now be included as a part of `EfwSfe`, so it cannot depend on packages that depend on `EfwSfe`

[EFW-874] Clean up dependencies
