untangle/mfw_feeds

sync-settings/files/untangle-board-name.init
=> MFW-788: untangle-board-name: Shorten vmware board name to 'VMware'

sync-settings/Makefile, sync-settings/files/speedtest.sh
Use speedtest-cli for determining wan bandwidth instead of our
home grown tests
MFW-780
=> MFW-780: sync-settings: Switch to speedtest-cli

speedtest-cli/Makefile, speedtest-cli/patches/0001-Switch-to-python3.patch, speedtest-cli/patches/0002-Add-simple-json-output-option.patch
=> MFW-1385 Update speedtest and patches.

configs/common/packages, wan-manager/files/wan-manager
- Adding the timeout utility.
- Adding functionality in wan-manager to query when an interface is offline, exclude it from any policy choices.
=> MFW-1590 wan-manager support for offline interfaces

bctid/Makefile
=> Revert "Increase connection and thread pool for bctid"

bctid/Makefile
Need to upper the bctid threadpool and network connection pool to accommodate not doing caching in packetd.
=> Mfw 1743 master

kmod-vhost/Makefile, libpktdpdk/Makefile, libpktdpdk/files/dpdkclient.sh
Added Makefile to mfw_feeds/libpktdpdk
Added dpdkclient.sh to mfw_feeds/libpktdpdk/files
Fixed typo in mfw_feeds/kmod-vhost
=> MFW-2451 Added libpktdpdk

alertd/Makefile
This reverts commit 63f2820ca98c2280875c8203a58b950c7f557b09.
=> Revert "MFW-2248 Send alert command. (#148)"

.vscode/tasks.json, .vscode/vsbuild.sh, configs/common/mfw_packages, credentials/Makefile, credentials/files/credentials.json
https://jira.untangle.com/browse/MFW-2627
=> Mfw 2627 credentials file

wan-manager/files/wan-manager
Add criteria_always_up for MFW-2718
=> Mfw 2718 ipsec failover issues (#165)

configs/dpdk/packages, libpktdpdk/Makefile
I'm not able to test this locally.
=> MFW-2769 Add gdb to image

pyconnector/files/pyconnector
https://jira.untangle.com/browse/MFW-2949
=> MFW 2949 sync ports with cmd

credentials/files/credentials.json
MFW-3044 Adding store appliance key
Linked PR for sync-settings: https://github.com/untangle/sync-settings/pull/401
=> MFW-3044 Adding store appliance key

sync-settings/Makefile
Changes and Testing has been updated in Ticket's comments
[Test and Changes](https://awakesecurity.atlassian.net/browse/MFW-3555?focusedCommentId=227571)
=> MFW-3555 : Ruby1 hybrid mode: packetd signaling sent before settings.json updated

bctid/Makefile, bctid/files/categories.json
MFW-3961 Adding categories.json for webroot categories
=> MFW-3961 Adding categories.json for webroot categories

meta.yaml
Task: [MFW-4343](https://awakesecurity.atlassian.net/browse/MFW-4343)
updated maintainer list in `meta.yaml`
[MFW-4343]: https://awakesecurity.atlassian.net/browse/MFW-4343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MFW-4343 Update maintainer list for all barney repositories 

classd/Makefile, classd/files/classd.init, packetd/files/packetd.init
=> merge hybrid mode work

sync-settings/Makefile
MFW-4811 Removing connectivity-check script
=> MFW-4811 Removing connectivity-check script

sync-settings/Makefile
Please check the comment for more details: https://awakesecurity.atlassian.net/browse/MFW-5008?focusedCommentId=242795
=> MFW-4882 Added the password-manager binary in sync-settings

meta.yaml
https://awakesecurity.atlassian.net/browse/MFW-5780
=> [MFW-5780] Add github bridge tests

barney.yaml
https://awakesecurity.atlassian.net/browse/MFW-5780
=> [MFW-5780] Fix test/mfw_pkg/mfw-feeds-rpm

configs/common/mfw_packages, secret-manager/Makefile, sync-settings/Makefile
=> MFW-5928 : Integrate build process of password-manager binary 

configs/common/mfw_packages, secret-manager/Makefile, sync-settings/Makefile
=> MFW-5928 : Integrate build process of password-manager binary
